import train_cnn_on_mnist_patch
import train_routers_in_sep_training_pmoe_on_mnist_patch
import train_experts_in_sep_training_pmoe_on_mnist_patch
import train_joint_training_pmoe_on_mnist_patch
import plot_sample_complexity_exp_mnist_patches

train_cnn_on_mnist_patch

train_routers_in_sep_training_pmoe_on_mnist_patch

train_experts_in_sep_training_pmoe_on_mnist_patch

train_joint_training_pmoe_on_mnist_patch

plot_sample_complexity_exp_mnist_patches
